### ISSUE TITLE
Running Locally on Arm64 / Apple Silicon

### ISSUE THREAD

**Issue by StevenXL** [restyled-io/restyled.io#309] opened 2024-04-09 16:44 UTC
After installing `restyle-path`, the following error results:

```
Unable to find image 'restyled/restyler:edge' locally
edge: Pulling from restyled/restyler
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

`uname -a` => `Darwin Stevens-MBP 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:33:00 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6031 arm64`.

**Comment by pbrisbin** [comment] 2024-04-09 16:46
Duplicate of https://github.com/restyled-io/restylers/issues/468, for the most part.

Help wanted ;)

**Comment by pbrisbin** [comment] 2024-04-09 16:49
Feel free to try [this workaround](https://github.com/restyled-io/restyler/issues/208#issuecomment-1593490455) from the linked comment trail and see if that gets your farther.

**Closed** 2024-08-02 15:20 UTC
